### ISSUE TITLE
good job, your code is clear and the page look nice, I have a small notes

### ISSUE THREAD

**Issue by meyadd** [mahmoudaboc/JavaScript2#1]
- the alignment of repository name and its details is not equal, you can add a style (clear: both;) for h2 tag (.name) in css class to resolve that 
- when you set the innerHTML for an element, it is not necessary to add its previous value because it will be empty, like this :
`let name = document.createElement("h2");`
`name.innerHTML = name.innerHTML + arr[i].name`

**Comment by mahmoudaboc** [comment]
Thank you for your feedback   , but the second note  is not clear for me .
