### ISSUE TITLE
extra if condition

### ISSUE THREAD

**Issue by ekocibar** [mahmoudaboc/JavaScript2#3]
https://github.com/mahmoudaboc/JavaScript2/blob/a79a654c9b546743572411770efdce77b413d2c0/Week2/HomeWorkWeek2Js2.js#L9

brother no need this condition, it cause, call the functions  more than as instructed
lets say for 15, three if  conditions that you set will be called but we need only below 2.

**Comment by mahmoudaboc** [comment]
yes , but I didnt understand how :)
